// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5mZJ5LL0D8y0cTH9Ffb1p9gnCFADK_7g',
    appId: '1:515955598049:web:af248560fdc633be344da0',
    messagingSenderId: '515955598049',
    projectId: 'drivit-9d759',
    authDomain: 'drivit-9d759.firebaseapp.com',
    storageBucket: 'drivit-9d759.firebasestorage.app',
    measurementId: 'G-4X6CTSM57W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm5qbSUox9sCxpQk7-aEVxc0KU_-HFSKI',
    appId: '1:515955598049:android:74444bc4eb9b0d60344da0',
    messagingSenderId: '515955598049',
    projectId: 'drivit-9d759',
    storageBucket: 'drivit-9d759.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEwElTBpriTR27WSfL--JU-b53uOSbwu8',
    appId: '1:515955598049:ios:5e58daff7e79f569344da0',
    messagingSenderId: '515955598049',
    projectId: 'drivit-9d759',
    storageBucket: 'drivit-9d759.firebasestorage.app',
    iosBundleId: 'com.drivit.driver',
  );
}
